### ISSUE TITLE
Service not starting

### ISSUE THREAD

**Issue by enannos** [mobitel-ltd/jira-to-matrix#135]
Hi,

I am trying to implement the jira-to-matrix but I am getting many errors.

 npm run start

> jira-matrix-bot@0.2.2 start /root/jira-to-matrix
> node src/app.js

/root/jira-to-matrix/src/modules/log.js:41
    if (logConfig.type === 'console' || logConfig.type === 'both') {
                  ^

TypeError: Cannot read property 'type' of undefined
    at getLogger (/root/jira-to-matrix/src/modules/log.js:41:19)
    at Object.<anonymous> (/root/jira-to-matrix/src/config/validate-config.js:3:44)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/jira-to-matrix/src/config/index.js:3:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jira-matrix-bot@0.2.2 start: `node src/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jira-matrix-bot@0.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-22T18_00_20_450Z-debug.log

Node version is 
v10.15.0

I have also used a jira-matrix-bot user, but with the same result.
Can you help me resolve the issue? Also tried with node 8, the same result.

Thank you

**Comment by grigori-gru** [comment]
Hi,

thanks for question, I forget to add it. You should check [config.example](https://github.com/mobitel-ltd/jira-to-matrix/blob/master/config.example.js#L46) file. There is a `log` property now to work with logger.

**Comment by enannos** [comment]
That did the trick, thanks!!!

Another question, what should I set at Jira(webhooks setup) as a URL? Can you help me with the Jira settings?

**Comment by w1r0x** [comment]
Just check all of events and point callback address to the running service. No additional setup need.

**Comment by enannos** [comment]
Hi,

just the URL at Jira needs to be like : http://IP:4100  ?

**Comment by w1r0x** [comment]
Yep, like that. But if your jira is dedicated, I recommend to place it behind nginx with https configured.

**Comment by enannos** [comment]
Cannot make it work... :(

At config.js , I have the ip address of Jira(running http, not https)
In Jira, I have the set as URL the IP:4100 of the server where jira-to-matrix runs.

Do I have to change something else?

**Comment by w1r0x** [comment]
No, it should work. Do you have something in logs? 
Does jira user have permissions to use api and to see project? 

Just try to create any task and you should to see new room in matrix.

And it is urgent to users login be the same in matrix and jira, like when you using ldap.

**Comment by enannos** [comment]
The user fi bot should also be in LDAP directory?

**Comment by w1r0x** [comment]
No, just usual matrix user.

**Comment by enannos** [comment]
I had a small progress...


But now I am getting this when I create an Issue.



 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at MatrixClient.InviteBot (/root/jira-to-matrix/src/matrix/api-client.js:140:22)
    at MatrixClient.emit (events.js:182:13)
    at _callee8$ (/root/jira-to-matrix/node_modules/matrix-js-sdk/lib/sync.js:1305:64)
    at tryCatch (/root/jira-to-matrix/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/root/jira-to-matrix/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/root/jira-to-matrix/node_modules/regenerator-runtime/runtime.js:114:21)
    at Generator.tryCatcher (/root/jira-to-matrix/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/root/jira-to-matrix/node_modules/bluebird/js/release/generators.js:97:49)
    at /root/jira-to-matrix/node_modules/bluebird/js/release/generators.js:201:15
    at processRoomEvent (/root/jira-to-matrix/node_modules/matrix-js-sdk/lib/sync.js:1324:55)
    at tryCatcher (/root/jira-to-matrix/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/root/jira-to-matrix/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/root/jira-to-matrix/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/root/jira-to-matrix/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/jira-to-matrix/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/jira-to-matrix/node_modules/bluebird/js/release/promise.js:569:18)
(node:17052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by enannos** [comment]
Incredible.... It works 👍 
Amazing really.

Had some 401 and 403 errors, had to activate in Jira a new Jira User Server with the IP of jira-to-matrix as exception and use a User that exists in Matrix and Jira and have on both systems admin rights.

You did a great job, many thanks :

**Comment by grigori-gru** [comment]
Hope you will use it further! I'm going to update readme today to add more information about how it works and what it can, it's in russian only now. If you found some bugs or something is not clear for you create issue and we will help!
